name: SonarCloud Analysis

on:
  push:
    branches:
      - master  # Cambiar al nombre de la rama principal de tu repositorio

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
       with:
          java-version: 11
          distribution: 'zulu'
          distribution-version: '11.0.13'
    
    - name: Restore NuGet packages
      run: nuget restore
    
    - name: Build Android project
      run: msbuild /t:Restore,Rebuild /p:Configuration=Release /p:Platform="Any CPU" ./TripTimeLine/TripTimeLine.Android.csproj
    
    - name: Build iOS project
      run: msbuild /t:Restore,Rebuild /p:Configuration=Release /p:Platform="iPhone" ./TripTimeLine/TripTimeLine.iOS.csproj
    
    - name: Build Shared project
      run: msbuild /t:Restore,Rebuild /p:Configuration=Release /p:Platform="Any CPU" ./TripTimeLine/TripTimeLine.csproj
    
    - name: Run SonarCloud analysis
      run: dotnet sonarscanner begin /k:"nnovalbos_TripTimeLine" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.organization="nnovalbos"
    
    - name: Build and analyze
      run: dotnet build && dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"