name: SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarcloud-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    container:
      image: sonarsource/sonar-scanner-cli:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: SonarCloud Scan
      run: sonar-scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

