name: SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarcloud-analysis:
    name: SonarCloud Analysis
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          distribution-version: '11.0.13'

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Install SonarScanner
        run: |
          brew install sonar-scanner
          echo "sonar.host.url=https://sonarcloud.io" >> $GITHUB_WORKSPACE/sonar-project.properties
          echo "sonar.projectKey=nnovalbos_TripTimeLine" >> $GITHUB_WORKSPACE/sonar-project.properties
          echo "sonar.organization=nnovalbos" >> $GITHUB_WORKSPACE/sonar-project.properties

      - name: SonarCloud Scan
        run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
